server:
  port: 8082

spring:
  application:
    name: DOCTOR-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/medicnote_doctor
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: DOCTOR-SERVICE:8082
    prefer-ip-address: false

logging:
  level:
    root: INFO
    com.MedicNote.doctorService: INFO
    org.hibernate.SQL: WARN

jwt:
  secret: k2x7ieCfxLcw5us4+mP+7tspXHhVfGn+kzVVheSrsT0=   # same in ALL services
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html