server:
  port: 8084

spring:
  application:
    name: PRESCRIPTION-SERVICE

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/medicnote_prescription
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: jagadhesh.85131@gmail.com
    password: hnod tpdh stxd mqhs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: PRESCRIPTION-SERVICE:8084
    prefer-ip-address: false

logging:
  level:
    root: INFO
    com.MedicNote.prescriptionService: INFO
    org.hibernate.SQL: WARN

jwt:
  secret: k2x7ieCfxLcw5us4+mP+7tspXHhVfGn+kzVVheSrsT0=   # same in ALL services
  expiration: 86400000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

resilience4j:
  circuitbreaker:
    instances:
      doctorService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
      patientService:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html