server:
  port: 8080

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**

        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/api/doctors/**

        - id: patient-service
          uri: lb://PATIENT-SERVICE
          predicates:
            - Path=/api/patients/**

        - id: prescription-service
          uri: lb://PRESCRIPTION-SERVICE
          predicates:
            - Path=/api/prescriptions/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  main:
    web-application-type: reactive

jwt:
  secret: k2x7ieCfxLcw5us4+mP+7tspXHhVfGn+kzVVheSrsT0=  # same in ALL services

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
